---

- hosts: all 
  become: true
  tasks:

  - name: install update (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"



- hosts: web_servers
  become: true
  tasks:

  - name: update repository index
    #tags: always
    apt:
      update_cache: yes
    when: ansible_distribution in ["Ubuntu","Debian"]

  - name:  install apache2 and php package
    tags: apache,apache2,ubuntu
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache
    tags: php package
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package (Ubuntu)
    tags: samba
    package:
      name: samba 
      state: latest
